# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - 'master'

pool:
  vmImage: ubuntu-latest

#name a variable
variables:
- name: 'Enbai Kuang'
  value: 'me'
pr: 'none'

#groups sequential actions
stages:
  - stage:
    jobs: 
      - job: 'build'
        steps:
          - script: "dotnet build 'Project0/Project0/Project0.csproj'"
          - script: echo "oh hey $(Enbai Kuang)"
      - job: 'test'
        dependsOn: 'build'
        steps:
          - script: "dotnet test 'Project0/Project0/Project0.csproj'"
      - job: 'publish'
        dependsOn: 'test'
        steps:
          - script: "dotnet publish 'Project0/Project0/Project0.csproj'"

name: '$(date:yyyMMdd)$(rev:r)'
